### ISSUE TITLE
1.7.10 support

### ISSUE THREAD

**Issue by bradenbest** [GiantLuigi4/Smaller-Units#1]
requesting 1.7.10 support. 1.7.10 is already a well-supported version in terms of mods.

**Comment by GiantLuigi4** [comment]
Already exists, but it's not by me, and is no longer downloadable afaik.
Little blocks mod (which this mod is inspired by) is literally what you are asking for, lol.

**Comment by bradenbest** [comment]
And little blocks itself (at least what little can be found in terms of download links) is broken (report says it crashes upon crafting the dirt block recipe). Oof. That's unfortunate.

**Comment by bradenbest** [comment]
In case you were wondering, I'm helping a group of players build a modpack for a server. My role is as an organizer and tester (making sure they load and function at the most basic level, such as portals taking you to a dimension without crashing the game or items from a mod appearing in the item roster). LittleBlocks was one of the mods, and the only two alternatives were this and LittleTiles, which we ended up going with. I appreciate you taking the time to look at this issue, though. Cheers!

**Comment by GiantLuigi4** [comment]
You actually happened to post this issue the day before I went back to working on this mod, lol.
Anyway, I might be able to help with that little blocks crash if you give me the log.
