### ISSUE TITLE
Sign Crash

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#100]
- Got issue 100, yoink! -
If you place a sign on a complete SU Area the game will crash (will provide image shortly)
[debug.log](https://github.com/GiantLuigi4/Smaller-Units/files/6094231/debug.log)
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/6094232/latest.log)
[crash-2021-03-05_18.17.00-client.txt](https://github.com/GiantLuigi4/Smaller-Units/files/6094233/crash-2021-03-05_18.17.00-client.txt)

**Comment by GiantLuigi4** [comment]
10/10, reproduced it instantly

**Comment by SonicJDF** [comment]
![2021-03-05_18 19 26](https://user-images.githubusercontent.com/52858386/110187832-5f00d080-7ddf-11eb-9b75-79d21924d788.png)
incase that was sarcastic, here's a photo

**Comment by GiantLuigi4** [comment]
I actually did reproduce it pretty much instantly.

**Comment by SonicJDF** [comment]
Fixed, however #36
