### ISSUE TITLE
Wall Hitboxes

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#101]
- Whenever a issue happens, make sure to have a teddy bear on hand! -

Wall hitboxes don't work as they should in vanilla
![2021-03-05_18 39 16](https://user-images.githubusercontent.com/52858386/110188682-34fcdd80-7de2-11eb-80d5-aac001d4c283.png)

**Comment by GiantLuigi4** [comment]
same with every block that has a different collision box from hitbox if I'm not mistaken

**Comment by SonicJDF** [comment]
Fences work fine.

**Comment by GiantLuigi4** [comment]
![image](https://user-images.githubusercontent.com/49770992/110189839-9a56cb80-7dee-11eb-84b0-f594aad36b71.png)
fixed
