### ISSUE TITLE
Taking the book off a lecturn does not give it back

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#115]
- you ruined my reading experience and my day is devastated.

**Comment by SonicJDF** [comment]
until the UI for the book is cleared *

**Comment by GiantLuigi4** [comment]
#115 is clearly able to be closed then
edit: I mean #72

**Comment by GiantLuigi4** [comment]
if I had to guess, I'm preventing the GUI from naturally closing and the game waits until the GUI is closed to actually resync the inventory

**Comment by GiantLuigi4** [comment]
*lectern
I make that mistake all the time too

but this has been fixed

https://user-images.githubusercontent.com/49770992/147843424-cda2ca11-5a37-44e8-9822-7af0fd763cf9.mov
