### ISSUE TITLE
Falling blocks don't work correctly

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#118]
- Pop goes the weasel! 
Before breaking bottom block
![2021-03-10_19 22 13](https://user-images.githubusercontent.com/52858386/110721346-fbf3ad00-81d5-11eb-85c9-6ac61a5c03c7.png)
After
![2021-03-10_19 22 18](https://user-images.githubusercontent.com/52858386/110721358-031abb00-81d6-11eb-9171-28c9f0364e3e.png)

**Comment by GiantLuigi4** [comment]
just did a full stack of 64 of them, not a single one broke
however I don't know that that's vanilla behavior either <:thonk4:786665253458149382>
*checks*
yep, it is
