### ISSUE TITLE
Rails can be duped from Slime blocks

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#122]
![2021-04-29_20 46 14](https://user-images.githubusercontent.com/52858386/116638497-115e9b00-a92c-11eb-8b30-9a74e7697818.png)

**Comment by GiantLuigi4** [comment]
<@380845972441530368>

**Comment by GiantLuigi4** [comment]
tried it, game died before I could activate the piston lol

**Comment by GiantLuigi4** [comment]
tried it again, fixed
