### ISSUE TITLE
How do you get these?

### ISSUE THREAD

**Issue by qwertious** [GiantLuigi4/Smaller-Units#124]
In the creative inventory, you can only get 4x4 and 8x8 SUs in 1.16. Also, I can't get the hammers to work. Is there any way to get the 2x2 SU or any smaller than 8x8?

**Comment by GiantLuigi4** [comment]
Try the one from the discord, also the hammers are crafting items.

https://cdn.discordapp.com/attachments/723243821839941753/838224271004008489/smallerunits-1.16.jar

**Comment by qwertious** [comment]
Thank you!

**Comment by qwertious** [comment]
What about the 128x128?

**Comment by GiantLuigi4** [comment]
configs

**Comment by SonicJDF** [comment]
This can be closed.
