### ISSUE TITLE
Forget the sign crash, this is signageddon

### ISSUE THREAD

**Issue by qwertious** [GiantLuigi4/Smaller-Units#125]
When I place a sign in a SU, it doesn't crash, but it doesn't let me type anything and instantly escapes the text screen. When I try to place a block after this, it just breaks the block I look at instantly. Also, I cannot pick up items (At least the sign items I broke) and when I throw an item it just vanishes. Sign items are also glitched, but that could just be normal Minecraft. I cannot spawn mobs (even with the /summon command) (even though a wandering trader appeared), and I cant place any blocks (Even replace blocks with /setblock). When I exit the world, the game crashes.

I had the Create mod installed when this happened, and I was using version 1.16 (mod version 1.0) found on Curseforge.

**Comment by qwertious** [comment]
I can't replicate it again for some reason, but it doesn't let me type in the instantly vanishing box still.

**Comment by SonicJDF** [comment]
Something extremely similar has been reported to this before, this can be be closed. Not to mention no actual log was provided with the crash which is a huge thing.
