### ISSUE TITLE
Place smaller place automaticly goes to a corner

### ISSUE THREAD

**Issue by lublak** [GiantLuigi4/Smaller-Units#127]
If you reduce a block and then place it, it will automatically "teleport" to a corner.
In general, the poisition you have clicked on should be perforated.
In addition, the yellow corners are displayed for a short time.

If I may add another wish, I would like it if this yellow bean were to be automatically deleted after all blocks have been removed.
And that this yellow beacon is not displayed at all.

Also i can't add new "small" blocks to this zone.

**Comment by GiantLuigi4** [comment]
uhh, what?

**Comment by lublak** [comment]
1. part: make a block smaller 
![grafik](https://user-images.githubusercontent.com/44057030/124337600-ae93b500-dba3-11eb-8767-5f7d9912fba6.png)
than just place it in the world. Everytime the border blinks 
![grafik](https://user-images.githubusercontent.com/44057030/124337624-cbc88380-dba3-11eb-8777-c5c044fa3097.png)
also the blocks goes to a corner not to the position of the "click"

2. my wish. I don't want to play with the yellow border. It would be nice to have a: I need to make my block small mode. So every block needs to be shrinked.
After i remove all the blocks frome the "yellow" zone, the zone gets removed automaticly.

3. i have a zone 1/8 but i can't place 1/8 blocks in it, only full blocks.
I think its the same as 2.

**Comment by GiantLuigi4** [comment]
so, I don't know why I have it setup so that you can shrink blocks, but, what you're doing when you place the small block, is you're creating a field of small blocks 
If you try to place a block on the block you placed the unit in, you will place a small block

**Comment by GiantLuigi4** [comment]
if you just put the hammer in the crafting grid alone, then place the item you get out of that, you'd see why the yellow things are there

**Comment by lublak** [comment]
hmmm okay, so is more a feature request than a bug, to make a mode, that works without the yellow thing. So you can create micro blocks and first place: auto create invible zone for micro blocks and also put the block in the correct location not to the corner: 
![grafik](https://user-images.githubusercontent.com/44057030/124338055-3084dd80-dba6-11eb-96d5-a1510edfb435.png)
(btw i placed the small block in the center)
every other block: only place if 1/8 block = 1/8 zone
if remove last block in the zone, just remove the zone.

**Comment by GiantLuigi4** [comment]
so, the reason I have it as is, is because I'm partially following the original mod (little blocks), and giving more quality of life features
for naturally created units (sugar cane growth, pistons moving, etc), the zone will be removed automatically
I've had this requested multiple times, but I'm honestly unsure if I *should* implement it
Also, the reason it places in the corner, is because I'm just generating the result of ctrl+pickblock

**Comment by lublak** [comment]
Hmmm. I can only say that's more vanilla like if you work with small blocks instance of yellow zones.
Also it can be a option:
mode = original or mode = vanilla
