### ISSUE TITLE
Chest Animations

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#134]
If a chest is spam right clicked, the animation can freeze.
![2021-07-09_21 07 29](https://user-images.githubusercontent.com/52858386/125148737-fe213600-e0f9-11eb-97fd-6a0fcd86c175.png)

**Comment by SonicJDF** [comment]
Surprised this isn't fixed yet.

**Comment by GiantLuigi4** [comment]
I don't think I can fix it, the fact that it works in normal scale is amazing to me

**Comment by GiantLuigi4** [comment]
fixing #92 has also fixed this
