### ISSUE TITLE
Trapped Chest Animations

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#135]
Trapped chest do not display an animation if redstone wire is connected to it.

**Comment by SonicJDF** [comment]
Fixed.

**Comment by GiantLuigi4** [comment]
ye

**Comment by GiantLuigi4** [comment]
happened a decent while ago, when I moved blocks being placed and removed off to a custom packet instead of just sending the entire freaking unit tile entity's nbt data
