### ISSUE TITLE
Incorrect Shulker Beahvior

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#138]
Shulkers when blocked by a block shouldn't be able to open, however the shulker opens anyways as it doesn't care what the human thinks is possible.
![2021-07-09_21 45 03](https://user-images.githubusercontent.com/52858386/125149488-f1eba780-e0fe-11eb-9559-0515cb76c12e.png)

**Comment by GiantLuigi4** [comment]
fixed
