### ISSUE TITLE
Sign (CRASH!)

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#142]
Placing a sign in a SU area then breaking the SU area will crash the game.

**Comment by SonicJDF** [comment]
[crash-2021-07-07_17.07.18-client.txt](https://github.com/GiantLuigi4/Smaller-Units/files/6794585/crash-2021-07-07_17.07.18-client.txt)

**Comment by GiantLuigi4** [comment]
I think that’s the wrong log

**Comment by SonicJDF** [comment]
Crash Fixed. #36
