### ISSUE TITLE
Pressing F3 + T (Reloading Resources) (CRASH!)

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#144]
When you press F3 + T it causes the game to crash.
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/6794603/latest.log)

**Comment by GiantLuigi4** [comment]
can't reproduce

**Comment by SonicJDF** [comment]
Can't reproduce, closed.

**Comment by GiantLuigi4** [comment]
~~knowing my luck, it'll happen if you reload resources 20 times in a row or smth~~
