### ISSUE TITLE
Heavy Lag w/ Better Weather

### ISSUE THREAD

**Issue by WenXin20** [GiantLuigi4/Smaller-Units#148]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Smaller Units` - Latest on discord from 7/8/21
[`Better Weather v2.0-seasons-only-4`](https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3325325)

When you do: 
1. Place a block in a smaller unit
2. Lag

What should happen:
- No lag.

What happens instead:
- Instead the game lags hardcore where I can't even more my player anymore and I am forced to close the game. The log also starts to spam an error message:
[Error log](https://gist.github.com/WenXin20/8c8208baa42fa80086db65d94ad8a440)

**Comment by GiantLuigi4** [comment]
it's actually not lag, but instead the game melting down for... reasons... which I'm not entirely sure about
anyway, this issue has been fixed
