### ISSUE TITLE
SU Dimensional Crash!

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#152]
SU Blocks placed in the Overworld (Will work in any dimension) then ctrl clicked and placed into a different dimension, crash the game.

[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/6852352/latest.log)
[crash-2021-07-20_21.21.27-server.txt](https://github.com/GiantLuigi4/Smaller-Units/files/6852356/crash-2021-07-20_21.21.27-server.txt)

**Comment by GiantLuigi4** [comment]
doesn't matter if it is a pickblocked unit

**Comment by GiantLuigi4** [comment]
![image](https://user-images.githubusercontent.com/49770992/126835109-15b80407-b135-4a86-b265-bda8753e61bd.png)
fixed
