### ISSUE TITLE
Texture issue for Redstone Dust

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#162]
When a piece of redstone is broke, the other pieces do not update there texture
![2021-11-19_19 10 05](https://user-images.githubusercontent.com/52858386/142708907-d7b67a00-bb05-4e2d-9479-aa730914106f.png)
.

**Comment by GiantLuigi4** [comment]
*diagonal neighbors :pain:*

**Comment by GiantLuigi4** [comment]
This should’ve been fixed

**Comment by GiantLuigi4** [comment]
it is indeed fixed
