### ISSUE TITLE
[1.18, Bug] Stalactites can't fill up Cauldrons

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#167]
![2022-05-31_16 54 15](https://user-images.githubusercontent.com/52858386/171290688-7691ee01-7164-4b09-a040-c59529d1b815.png)

*This bug happens for both water and lava*

**Comment by GiantLuigi4** [comment]
Seems like the cause of this is random ticking being broken

**Comment by GiantLuigi4** [comment]
Pretty sure this one’s also been fixed

**Comment by GiantLuigi4** [comment]
yep
