### ISSUE TITLE
[1.18, Bug] Incorrect hitboxes

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#173]
![2022-06-02_01 09 08](https://user-images.githubusercontent.com/52858386/171564315-599315c5-98c5-4905-ac86-3150e836cd9b.png)

This occurs on Flowers and Bamboo

**Comment by GiantLuigi4** [comment]
Looks right to me

**Comment by GiantLuigi4** [comment]
![image](https://github.com/GiantLuigi4/Smaller-Units/assets/49770992/e4790408-ef96-4feb-9dac-5db53ba6684f)
had to think for a second about why the issue occurred in the first place
does not occur with current systems
