### ISSUE TITLE
[Request] Namable SU units

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#174]
I think it'd be pretty cool if you could name SU blocks in Anvils and upon hovering, would show the name above them. This would be useful when you are dealing with a ton of SU areas and keeping track of what connects to what parts.

![2022-06-02_15 08 49](https://user-images.githubusercontent.com/52858386/171733225-0a58f88c-4c14-47e9-a3f9-086f84e56719.png)

**Comment by GiantLuigi4** [comment]
yea, I can do that
