### ISSUE TITLE
[1.18, Bug] Double Block Seperation

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#175]
If you place a double block while a full block is above it, it'll cut the bottom part and still place the top part (other words it doesn't check for both parts)

![2022-06-02_15 46 57](https://user-images.githubusercontent.com/52858386/171735540-52e80c0a-bfd4-4fe7-a3d7-21fa55797451.png)
![2022-06-02_15 47 08](https://user-images.githubusercontent.com/52858386/171735554-9dd88871-b745-4328-9ba4-ffd23f60f33b.png)
![2022-06-02_15 48 02](https://user-images.githubusercontent.com/52858386/171735563-b74cfb68-ee69-4d06-9f26-fbaaf3989f7e.png)

**Comment by GiantLuigi4** [comment]
This has infact been fixed
