### ISSUE TITLE
[1.18, Bug] Minecarts freak out if the Rail under them is broken

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#178]
![ezgif com-gif-maker (26)](https://user-images.githubusercontent.com/52858386/172268514-eb87f728-4e04-40f3-927a-3ae967c45e80.gif)

**Comment by GiantLuigi4** [comment]
Oh I think I fixed this

**Comment by GiantLuigi4** [comment]
yep
