### ISSUE TITLE
[1.18, Bug] Daylight sensor crashes game

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#183]
Daylight sensor upon being placed in SU unit (while it was raining) crashed the game

[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/10018024/latest.log)

**Comment by GiantLuigi4** [comment]
Same crash that beacons have

**Comment by GiantLuigi4** [comment]
is fixed
