### ISSUE TITLE
[1.18, Bug] Cannot break Powdered Snow and String

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#184]
(You also are unable to Bucket the Powdered snow to instantly break it)

![2022-11-15_22 14 48](https://user-images.githubusercontent.com/52858386/202082230-37eb8f03-b07e-4e8a-bc88-070a09ddfcbb.png)

(Will continue to update this list with more blocks I find)

**Comment by SonicJDF** [comment]
Open gates cannot be destroyed or closed. This state can be reversed using Redstone

**Comment by SonicJDF** [comment]
Big Dripleafs in Full Tilt State are unable to be broken, Bamboo cannot be broken (and can't be bonemealed) this issues seems to occur to all flowers.

**Comment by GiantLuigi4** [comment]
Any block which lacks a collision shape
