### ISSUE TITLE
[1.18, Bug] End Portal is Invisible

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#185]
![2022-12-07_21 54 35](https://user-images.githubusercontent.com/52858386/206352932-82527ff4-654a-4e15-898a-e9826f318589.png)

**Comment by GiantLuigi4** [comment]
![image](https://user-images.githubusercontent.com/49770992/206353030-477403ce-5935-4538-8c88-fc2984dbcec5.png)
did not reproduce, what are your coords

**Comment by GiantLuigi4** [comment]
ok so this happens when at negative coordinates, and it's block entities in general, not just portals
