### ISSUE TITLE
[1.18, Bug] Campfires produce particles regardless of status

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#188]
![2023-01-31_17 43 37](https://user-images.githubusercontent.com/52858386/215909278-0c895fb0-fb89-46b5-acea-ce9a37affa80.png)

**Comment by GiantLuigi4** [comment]
thonkhuh

**Comment by GiantLuigi4** [comment]
this has been fixed apparently
