### ISSUE TITLE
[1.19.2, Forge, Bug] Sculk sensors do not pickup sounds

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#208]
-- Describe how you caused the bug --
Attempted to use sculk sensor
-- Describe the expectation --
Expected Sculk Sensor to function
-- Describe what happened instead --
It didn't function

-- Additional info --
SU Version: 2.1.3
Exact MC Version: 1.19.2 
Loader: Forge
Any optimization mods: None

**Comment by GiantLuigi4** [comment]
apparently I fixed this
