### ISSUE TITLE
[1.19.2, Forge, Bug] Wax visuals and sound don't work

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#209]
-- Describe how you caused the bug --
Wax a Copper Block
-- Describe the expectation --
Yellow particles appear as well as the sound effect to accompy the effect
-- Describe what happened instead --
Nothing visually shows up, however the block will not rust any further.

-- Additional info --
SU Version: 2.1.3
Exact MC Version: 1.19.2 
Loader: Forge
Any optimization mods: None

**Comment by GiantLuigi4** [comment]
resolved
