### ISSUE TITLE
Sugar Cane is unable to be placed next to each other.

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#30]

**Comment by GiantLuigi4** [comment]
Did you try giving it a support block and some water? (Which yes, I know water is completely bugged rn)

**Comment by SonicJDF** [comment]
Yes a support block but I can't do water cause ya know... it doesn't work.

**Comment by SonicJDF** [comment]
For now I'll close the issue till Water works
