### ISSUE TITLE
Piston Freezing

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#33]
If you place a block while a piston has it's head out, it'll freeze in place
![2021-02-14_22 15 17](https://user-images.githubusercontent.com/52858386/107904729-338e7280-6f12-11eb-8894-e700edb0326b.png)

**Comment by GiantLuigi4** [comment]
is this still a thing 🤔

**Comment by SonicJDF** [comment]
lemme test it.

**Comment by SonicJDF** [comment]
Fixed.
