### ISSUE TITLE
Signs are completely unfunctioning

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#36]

**Comment by GiantLuigi4** [comment]
Signs are kinda stupidly programmed, so I'm not sure how fixable this is

**Comment by SonicJDF** [comment]
Have you tried getting good?

**Comment by SonicJDF** [comment]
Absolutely and completely busted.

**Comment by SonicJDF** [comment]
I'm now going to use this post for any time a sign related issue comes up, I can link back to this.
