### ISSUE TITLE
Brewing stands do not work.

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#37]

**Comment by GiantLuigi4** [comment]
I’m assuming you mean the gui?

**Comment by SonicJDF** [comment]
Everything, GUI and Bottle Textures not appearing.

**Comment by GiantLuigi4** [comment]
GUI I forgot the mixin for, (hopefully I can find another way to prevent container closing at some point to make it “perfectly” mod compatible), bottle textures idk about though
