### ISSUE TITLE
SU Cakes behave weirdly in Singleplayer if the person is holding a cake and places it on an partially eaten cake

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#40]

**Comment by GiantLuigi4** [comment]
Define?

**Comment by SonicJDF** [comment]
It's really hard to explain, if the player places a cake then places another cake on top, the cakes won't be able to be destroyed until the player switched to creative mode and eats the bottom cake

**Comment by SonicJDF** [comment]
Fixed.
