### ISSUE TITLE
Fronze Conduit, if a Conduit is properly powered then broken, the model will stay. 

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#49]
- Side Note: - The Conduit plays the sound of being powered on however neither does the model nor the actual effect of the conduit work.

**Comment by GiantLuigi4** [comment]
Fronze

**Comment by SonicJDF** [comment]
**Fronze** is now fixed, however side note for conduit not providing effects isn't.
