### ISSUE TITLE
Bonemealing Bambo outside of an SU Area (CRASH!)

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#51]
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/5984256/latest.log)

**Comment by GiantLuigi4** [comment]
can't reproduce this

**Comment by SonicJDF** [comment]
I just reproduced it, in a different world. have ya tried getting good?

**Comment by SonicJDF** [comment]
[Uploading latest.log…]()

**Comment by SonicJDF** [comment]
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/5984972/latest.log)

**Comment by GiantLuigi4** [comment]
A temp "fix" has been put in place for this, granted it's merely try catching so I'll leave the issue open
