### ISSUE TITLE
Right clicking a full Respawn Anchor in the overworld (CRASH)

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#55]
- No, it won't let me do labels, even here. -

**Comment by GiantLuigi4** [comment]
huh, ok (to the not letting you add labels)

**Comment by SonicJDF** [comment]
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/5984356/latest.log)

**Comment by GiantLuigi4** [comment]
nether or overworld?

**Comment by GiantLuigi4** [comment]
the heck what? the crash is "at com.tfc.smallerunits.utils.FakeServerWorld.getGameTime".
does the respawn anchor even acknowledge time?

**Comment by SonicJDF** [comment]
No, and Overworld? I mean the thing said it in the title Luigi...

**Comment by GiantLuigi4** [comment]
welp, that's odd
