### ISSUE TITLE
When Sea Pickles are bonemealed on a Coral Block, if the SU Area next to it also has similar things the Pickle placed on the other SU Area will sometimes disappear.

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#61]

**Comment by SonicJDF** [comment]
![2021-02-15_16 58 43](https://user-images.githubusercontent.com/52858386/108000241-165bb180-6faf-11eb-984d-c40602a28ecd.png)
Example of said setup, these are 2 different SU Areas

**Comment by GiantLuigi4** [comment]
the sad part is I know exactly why this happens

**Comment by GiantLuigi4** [comment]
It was not why I thought it was, but instead how I was handling bonemeal in specific
