### ISSUE TITLE
Pressing F5 causes a crash

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#64]
wot
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/5984580/latest.log)
- My character was wearing Diamond Boots - Soul Speed 3 if this has anything to do with the crash 🤷 -

**Comment by SonicJDF** [comment]
The issue appears to be if the F5 camera would see SU Areas, if it doesn't F5 works perfectly fine, want world file?

**Comment by GiantLuigi4** [comment]
yea, world would be nice, I can't reproduce this

**Comment by SonicJDF** [comment]
please hold, no really hold onto ur table. thanks

**Comment by SonicJDF** [comment]
[World.zip](https://github.com/GiantLuigi4/Smaller-Units/files/5984587/World.zip)

**Comment by SonicJDF** [comment]
Likely fixed as I've never encountered it again, though I have absolutely no way of reproducing. Going to close it for now.
