### ISSUE TITLE
Food can't be placed on Campfires

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#71]

**Comment by SonicJDF** [comment]
Title changed due to similar bug in newer versions, Food can no longer be placed on campfires

**Comment by GiantLuigi4** [comment]
![image](https://user-images.githubusercontent.com/49770992/147842050-6055fc87-37a5-473a-b4d7-5be0159c8451.png)
can be put on
waiting to see if it comes off

I have waited, the result is yes
