### ISSUE TITLE
Activating a portal with Flint and steel using dispenser crashes the game

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#89]
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/6006179/latest.log)
[debug.log](https://github.com/GiantLuigi4/Smaller-Units/files/6006180/debug.log)
[crash-2021-02-18_16.06.07-server.txt](https://github.com/GiantLuigi4/Smaller-Units/files/6006181/crash-2021-02-18_16.06.07-server.txt)

**Comment by SonicJDF** [comment]
- Fixed Title -

**Comment by GiantLuigi4** [comment]
(Should be) fixed
