### ISSUE TITLE
Right clicking with a stray spawn egg in a SU Area crashes the game

### ISSUE THREAD

**Issue by SonicJDF** [GiantLuigi4/Smaller-Units#90]
[latest.log](https://github.com/GiantLuigi4/Smaller-Units/files/6006260/latest.log)
[crash-2021-02-18_16.24.00-client.txt](https://github.com/GiantLuigi4/Smaller-Units/files/6006263/crash-2021-02-18_16.24.00-client.txt)

**Comment by GiantLuigi4** [comment]
Fixed
