### ISSUE TITLE
Sugar cane growth causes units to be counted as non natural

### ISSUE THREAD

**Issue by GiantLuigi4** [GiantLuigi4/Smaller-Units#95]

**Comment by SonicJDF** [comment]
Fixed. *I can't close this one!*

**Comment by GiantLuigi4** [comment]
it's only for a single game tick where it is non-natural

**Comment by SonicJDF** [comment]
Does it still exist in newer versions then?

**Comment by GiantLuigi4** [comment]
probably

**Comment by GiantLuigi4** [comment]
this does appear to be fixed, but I'm not 100% convinced

**Comment by GiantLuigi4** [comment]
ye, it's fixed
