### ISSUE TITLE
Missing Localization

### ISSUE THREAD

**Issue by WenXin20** [GiantLuigi4/Smaller-Units#96]
`Minecraft v1.16.5`
`Forge v36.0.43`
`Smaller Units v1.0`

All blocks, items, and the creative tab is missing localization.

![2021-03-04_02 16 22](https://user-images.githubusercontent.com/12000593/109932999-8bf29d80-7c90-11eb-8777-e0ea9454e2c5.png)

**Comment by GiantLuigi4** [comment]
Yeah, I just haven’t bothered to do it yet

**Comment by SonicJDF** [comment]
Done. *Close this please*
