### ISSUE TITLE
Pick Block Crash

### ISSUE THREAD

**Issue by WenXin20** [GiantLuigi4/Smaller-Units#97]
`Minecraft v1.16.5`
`Forge v36.0.43`
`Smaller Units v1.0`

When trying to place multiple units within the same block space, I got a crash.
[Crash Report](https://gist.github.com/WenXin20/0f8ebfddaabc84cc785e1bdd7edb38e4)

**Comment by GiantLuigi4** [comment]
Thanks for the report on this.
I’m pretty sure I had the same thing happen on a server which has smaller units installed on it, but I don’t own the server and never actually got the log.
Anyway, I have but one question: *how* did you put a unit into a unit? I’m pretty sure I explicitly disabled that.

**Comment by WenXin20** [comment]
I think I was using the wrong version. I updated to the latest version from the website instead of the launcher and no more crashes.

**Comment by WenXin20** [comment]
I should also mention that the reason for the confusion was because the file name doesn't include a mod version number, so both myself and the curseforge launcher thought I was using the latest version. But this can be closed, I havent gotten this crash since updating.

**Comment by GiantLuigi4** [comment]
alright
